### ISSUE TITLE
How to install/run?

### ISSUE THREAD

**Issue by kdrzazga** [Victor0596647/PyShopTycoon#2]
/PyShopTycoon # python main.py
Traceback (most recent call last):
  File "/PyShopTycoon/main.py", line 1, in <module>
    from game import Game
  File "/PyShopTycoon/game.py", line 1, in <module>
    from rich import print
ModuleNotFoundError: No module named 'rich'

/PyShopTycoon # python game.py
Traceback (most recent call last):
  File "/PyShopTycoon/game.py", line 1, in <module>
    from rich import print
ModuleNotFoundError: No module named 'rich'

**Comment by Victor0596647** [comment]
Oh I forgot, you need to install the [rich module](https://github.com/Textualize/rich) and I am surprised that you are interested in this old python project.
